### ISSUE TITLE
Changing zoom level causes scroll position to change

### ISSUE THREAD

**Issue by rschev** [jkgenser/react-pdf-headless#10]
When you're scrolled far into a long PDF and change the zoom level, the viewer jumps to a different page. This is because the browser just remembers how many pixels deep you've scrolled. After changing zoom levels, your pages are taller or shorter, so this changes the place in the document that corresponds to that distance scrolled.

I've run into this same issue in my own pdf reader project and fixed it by tracking how far we are in the document as a percentage of the total document height. Then after changing the zoom level, we have a new total document height, and we can use the percentage to find the new position in pixels that matches where we were in the document.

You can see [the particular bit about recalculating the position here](https://github.com/xenit-eu/virtual-pdf-reader/blob/main/reader/src/components/MyPdfViewer.tsx#L105). Feel free to incorporate it into this project.

**Comment by AlfredMadere** [comment]
Two of the resizing events are related to these two lines in Page.tsx.

```typescript
          height: `${shouldRender ? 'fit-content' : `${virtualItem.size}px`}`,
          minHeight: `${virtualItem.size-100}px`

```

shouldRender is set to true before the renderPageLayer actually renders which results in the following behavior:

- shouldRender starts as false so the page size is equal to virtualItem.size
- shouldRender is set to true but there is no content in the pageLayer yet so the height is set to the minHeight which is 100px less than the virtualItem.size
- The content is rendered in the pageLayer and because the 'fit-content' class is now applied, the height of the page jumps back up to approximately virtualItem.size

**Comment by jkgenser** [comment]
@rschev thanks for this bug report! We just experienced this in our app so i'm going to get it fixed.

**Comment by ShashanKV98** [comment]
Hi @jkgenser I tested the demo, but increasing the zoom still scrolls the document to the top. Do you have any advice on how to fix this? Separately, I was actually trying out the mouse zoom, but the scrollbar keeps jumping up and down. Thanks and awesome work!

```
const newScaledOffsetWithGap = calculateAfterZoomOffset(virtualizer, currentScale, nextScale)
const rect = parentRef.current.getBoundingClientRect()
const x = mouseX - rect.left // X position relative to scroll
const y = (mouseY - rect.top) + newScaledOffsetWithGap // Y position relative to scroll  

...
// Both don't seem to work
parentRef.current.scrollTo([x,y])
virtualizer.scrollToOffset(y || virtualizer.scrollOffset, {
        align: 'start',
        behavior: 'auto',
      })
```
